version: "3"

services:

    rest-service:
        env_file: .env
        container_name: rest-service
        build: .
        # Migrating the database in the command where the server is runned is dangerous but
        # in this case simplifies execution
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/mopokemon
        ports:
          - "8000:8000"
          - "3000:3000"
    