# Generated by Django 3.0 on 2021-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='species name', max_length=50, unique=True, verbose_name='name'),
        ),
    ]
