# Generated by Django 3.0 on 2021-01-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20210123_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='evolves_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon.Species'),
        ),
    ]
